### ISSUE TITLE
Tests fail on Windows

### ISSUE THREAD

**Issue by sschuberth** [uwolfer/gerrit-rest-java-client#35]
I just realized `mvn -B test` failes on Windows with:

    testParseSingleUserInfos(com.urswolfer.gerrit.client.rest.http.accounts.AccountsParserTest)  Time elapsed: 0.005 sec  <<< FAILURE!
    com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
        at com.google.gson.JsonParser.parse(JsonParser.java:65)
        at com.urswolfer.gerrit.client.rest.http.common.AbstractParserTest.getJsonElement(AbstractParserTest.java:35)
        at com.urswolfer.gerrit.client.rest.http.accounts.AccountsParserTest.testParseSingleUserInfos(AccountsParserTest.java:70)
    Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 3 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1574)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
        at com.google.gson.JsonParser.parse(JsonParser.java:60)
        ... 36 more

So it seems this is because of the magic prefix (`)]}'`) in Gerrit's responses. Interestingly, I couldn't find any code that handles this magic prefix. So comes the test pass on Linux if the magic prefix is not stripped before the JSON string is passed to gson?

**Comment by uwolfer** [comment]
I remember having discussed this issue some time ago also with mGerrit developer.

Urs Wolfer:
> I wondered why Gson handles this correctly - and I have found this interesting documentation:
https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#nonexecuteprefix
> It seems to be a common case that APIs include these prefixes. When enabling "lenient parsing" it can handle it. I have found that calling `JsonParser().parse()` enables lenient parsing. Since it is officially supported and documented, I prefer to let Gson handle it and do not skip the first 5 chars.

Evan Conway (@p4r4n01d )
> I would be happy to go with lenient parsing, however after a lot of trying to figure out why it is failing when I test it I finally figured out that the reason is the different line endings. Gson matches `")]}\'\n"` where my json files are `")]}\'\r\n"`. From this, I am inclined to re-implement JsonParser.consumeNonExecutePrefix to optionally skip those characters and cater for both line endings.

So it looks like reading a file on Win leads in a different result as reading it on Linux. Probably this is even a bug in JsonParser?

**Comment by sschuberth** [comment]
Thanks for the info. I agree that Gson's check is a bit too strict. While I'll look into submitting a patch to Gson, the more straight-forward fix for now is too enforce LF line endings for the JSON test resources I'll submit a PR shortly.

**Comment by sschuberth** [comment]
@uwolfer @p4r4n01d FYI, [here's my attempt](https://github.com/google/gson/pull/810) to fix the line-ending issue upstream in Gson.
