### ISSUE TITLE
query fail with multi conditions

### ISSUE THREAD

**Issue by yuwei336** [uwolfer/gerrit-rest-java-client#86]
I created a new label:Autosubmit in my gerrit server. I need to use the label to do someting. But when I add the label to query, it will have some exceptions.

java.lang.IllegalArgumentException: Illegal character in query at index 62: http://aml-code-master.amlogic.com:8080/changes/?q=status:open (label:Code-Review=2 AND label:Autosubmit=1)&n=100&o=DETAILED_LABELS&o=DETAILED_ACCOUNTS
	at java.net.URI.create(Unknown Source)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:216)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:180)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestRest(GerritRestClient.java:172)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.requestJson(GerritRestClient.java:149)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.getRequest(GerritRestClient.java:118)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.get(ChangesRestClient.java:114)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient.access$0(ChangesRestClient.java:89)
	at com.urswolfer.gerrit.client.rest.http.changes.ChangesRestClient$1.get(ChangesRestClient.java:79)
	at com.aml.gerrit.MainEntry.run(MainEntry.java:73)
	at com.aml.gerrit.MainEntry.main(MainEntry.java:39)
Caused by: java.net.URISyntaxException: Illegal character in query at index 62: http://aml-code-master.amlogic.com:8080/changes/?q=status:open (label:Code-Review=2 AND label:Autosubmit=1)&n=100&o=DETAILED_LABELS&o=DETAILED_ACCOUNTS
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	... 12 more

**Comment by yuwei336** [comment]
If I use "http://aml-code-master.amlogic.com:8080/changes/?q=status:open (label:Code-Review=2 AND label:Autosubmit=1)&n=100&o=DETAILED_LABELS&o=DETAILED_ACCOUNTS" this url with Chrome browser, it work well.

**Comment by yuwei336** [comment]
I know the reason, we can not use ' ', we need use '+'.
If I use "changes.query("status:open+label:Code-Review=2+label:Autosubmit=1")", it will be ok.
Thanks!

**Comment by uwolfer** [comment]
@yuwei336: Do I understand correctly that:
1) it works when you enter the query with a + in the filer text field
2) it does not work when you enter a space in the filter text field

**Comment by uwolfer** [comment]
@yuwei336: I think you should call `QueryRequest#encode` before executing the query.

**Comment by uwolfer** [comment]
@yuwei336: Have you had time to check out my suggestion? Please let me know if it helps.

**Comment by yuwei336** [comment]
Sorry, late to reply. It's ok if I follow your suggestion. Thanks.
I updated the version to the latest: 0.8.18.

I found another bug:
if ( revisionApi.canRebase()) {
    changeApi = revisionApi.rebase();
    revisionApi = changeApi.current();
}

I want to check if a CL can be rebased or not. If yes, I want to rebase it first, otherwise maybe have some conflicts.

But I wll get a exception if I use canRebase api.

**Comment by uwolfer** [comment]
RevisionApi#canRebase is not implemented yet, see https://github.com/uwolfer/gerrit-rest-java-client/blob/master/src/main/java/com/urswolfer/gerrit/client/rest/http/changes/RevisionApiRestClient.java.

Feel free to implement it and create a pull request. I'm happy to support you.
